source 'https://rubygems.org'
ruby '2.2.2'

gem 'filesize'
gem 'gssapi'
gem 'rainbow', '>= 2.1.0', '< 2.2.0'
gem 'rake'
gem 'rspec_junit_formatter'
gem 'rubocop'
gem 'rubocop-junit-formatter'
gem 'table_print'
gem 'test-unit'
gem 'webhdfs'
